repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Pin to a specific tag of ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: local
    hooks:
      - id: pylint
        name: pylint (errors-only)
        entry: uv run pylint --errors-only --disable=E1120
        language: system
        types: [python]
